// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/xrun.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunRequest contains parameters for creating and starting a sandbox
type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`                                                                             // OCI image reference containing kernel and initrd
	Rootfs        string                 `protobuf:"bytes,3,opt,name=rootfs,proto3" json:"rootfs,omitempty"`                                                                           // Path to VM rootfs disk image
	Vcpus         uint32                 `protobuf:"varint,4,opt,name=vcpus,proto3" json:"vcpus,omitempty"`                                                                            // Number of vCPUs
	MemoryMb      uint32                 `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`                                                      // Memory size in MB
	Cmdline       string                 `protobuf:"bytes,6,opt,name=cmdline,proto3" json:"cmdline,omitempty"`                                                                         // Kernel command line
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional labels
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_api_proto_xrun_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_xrun_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_xrun_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *RunRequest) GetRootfs() string {
	if x != nil {
		return x.Rootfs
	}
	return ""
}

func (x *RunRequest) GetVcpus() uint32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *RunRequest) GetMemoryMb() uint32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *RunRequest) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *RunRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// RunResponse contains the result of a Run operation
type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // veth host IP (empty if network disabled)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_api_proto_xrun_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_xrun_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_xrun_proto_rawDescGZIP(), []int{1}
}

func (x *RunResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RunResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *RunResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

// StopRequest contains parameters for stopping a sandbox
type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // Force stop if true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_api_proto_xrun_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_xrun_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_xrun_proto_rawDescGZIP(), []int{2}
}

func (x *StopRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StopRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// StopResponse contains the result of a Stop operation
type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_api_proto_xrun_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_xrun_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_xrun_proto_rawDescGZIP(), []int{3}
}

func (x *StopResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StopResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// DeleteRequest contains parameters for deleting a sandbox
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // Force delete if running
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_proto_xrun_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_xrun_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_xrun_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// DeleteResponse contains the result of a Delete operation
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_proto_xrun_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_xrun_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_xrun_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetRequest contains parameters for getting sandbox info
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_proto_xrun_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_xrun_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_xrun_proto_rawDescGZIP(), []int{6}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetResponse contains sandbox information
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *Sandbox               `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_proto_xrun_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_xrun_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_xrun_proto_rawDescGZIP(), []int{7}
}

func (x *GetResponse) GetSandbox() *Sandbox {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

// ListRequest contains parameters for listing sandboxes
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       map[string]string      `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional filters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_proto_xrun_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_xrun_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_xrun_proto_rawDescGZIP(), []int{8}
}

func (x *ListRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

// ListResponse contains a list of sandboxes
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandboxes     []*Sandbox             `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_proto_xrun_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_xrun_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_xrun_proto_rawDescGZIP(), []int{9}
}

func (x *ListResponse) GetSandboxes() []*Sandbox {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

// Sandbox represents a microVM sandbox
type Sandbox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Vcpus         uint32                 `protobuf:"varint,4,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMb      uint32                 `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Rootfs        string                 `protobuf:"bytes,7,opt,name=rootfs,proto3" json:"rootfs,omitempty"`
	IpAddress     string                 `protobuf:"bytes,8,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sandbox) Reset() {
	*x = Sandbox{}
	mi := &file_api_proto_xrun_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sandbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sandbox) ProtoMessage() {}

func (x *Sandbox) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_xrun_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sandbox.ProtoReflect.Descriptor instead.
func (*Sandbox) Descriptor() ([]byte, []int) {
	return file_api_proto_xrun_proto_rawDescGZIP(), []int{10}
}

func (x *Sandbox) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sandbox) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Sandbox) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Sandbox) GetVcpus() uint32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *Sandbox) GetMemoryMb() uint32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *Sandbox) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Sandbox) GetRootfs() string {
	if x != nil {
		return x.Rootfs
	}
	return ""
}

func (x *Sandbox) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Sandbox) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Sandbox) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// SnapshotRequest contains parameters for creating a snapshot
type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // Sandbox ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // Snapshot name
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_api_proto_xrun_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_xrun_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_xrun_proto_rawDescGZIP(), []int{11}
}

func (x *SnapshotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SnapshotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SnapshotRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// SnapshotResponse contains the result of a Snapshot operation
type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_api_proto_xrun_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_xrun_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_xrun_proto_rawDescGZIP(), []int{12}
}

func (x *SnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SnapshotResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// RestoreRequest contains parameters for restoring from a snapshot
type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	NewId         string                 `protobuf:"bytes,2,opt,name=new_id,json=newId,proto3" json:"new_id,omitempty"` // New sandbox ID after restore
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_api_proto_xrun_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_xrun_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_xrun_proto_rawDescGZIP(), []int{13}
}

func (x *RestoreRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *RestoreRequest) GetNewId() string {
	if x != nil {
		return x.NewId
	}
	return ""
}

// RestoreResponse contains the result of a Restore operation
type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_api_proto_xrun_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_xrun_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_xrun_proto_rawDescGZIP(), []int{14}
}

func (x *RestoreResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RestoreResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_api_proto_xrun_proto protoreflect.FileDescriptor

const file_api_proto_xrun_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/xrun.proto\x12\x04xrun\"\x88\x02\n" +
	"\n" +
	"RunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x16\n" +
	"\x06rootfs\x18\x03 \x01(\tR\x06rootfs\x12\x14\n" +
	"\x05vcpus\x18\x04 \x01(\rR\x05vcpus\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\rR\bmemoryMb\x12\x18\n" +
	"\acmdline\x18\x06 \x01(\tR\acmdline\x124\n" +
	"\x06labels\x18\a \x03(\v2\x1c.xrun.RunRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\vRunResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\"3\n" +
	"\vStopRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"4\n" +
	"\fStopResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"5\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\" \n" +
	"\x0eDeleteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\vGetResponse\x12'\n" +
	"\asandbox\x18\x01 \x01(\v2\r.xrun.SandboxR\asandbox\"\x83\x01\n" +
	"\vListRequest\x128\n" +
	"\afilters\x18\x01 \x03(\v2\x1e.xrun.ListRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\fListResponse\x12+\n" +
	"\tsandboxes\x18\x01 \x03(\v2\r.xrun.SandboxR\tsandboxes\"\xce\x02\n" +
	"\aSandbox\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x14\n" +
	"\x05vcpus\x18\x04 \x01(\rR\x05vcpus\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\rR\bmemoryMb\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x16\n" +
	"\x06rootfs\x18\a \x01(\tR\x06rootfs\x12\x1d\n" +
	"\n" +
	"ip_address\x18\b \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x121\n" +
	"\x06labels\x18\n" +
	" \x03(\v2\x19.xrun.Sandbox.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x01\n" +
	"\x0fSnapshotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\x06labels\x18\x03 \x03(\v2!.xrun.SnapshotRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x10SnapshotResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\"H\n" +
	"\x0eRestoreRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x15\n" +
	"\x06new_id\x18\x02 \x01(\tR\x05newId\"7\n" +
	"\x0fRestoreResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state2\xee\x02\n" +
	"\x0eSandboxService\x12*\n" +
	"\x03Run\x12\x10.xrun.RunRequest\x1a\x11.xrun.RunResponse\x12-\n" +
	"\x04Stop\x12\x11.xrun.StopRequest\x1a\x12.xrun.StopResponse\x123\n" +
	"\x06Delete\x12\x13.xrun.DeleteRequest\x1a\x14.xrun.DeleteResponse\x12*\n" +
	"\x03Get\x12\x10.xrun.GetRequest\x1a\x11.xrun.GetResponse\x12-\n" +
	"\x04List\x12\x11.xrun.ListRequest\x1a\x12.xrun.ListResponse\x129\n" +
	"\bSnapshot\x12\x15.xrun.SnapshotRequest\x1a\x16.xrun.SnapshotResponse\x126\n" +
	"\aRestore\x12\x14.xrun.RestoreRequest\x1a\x15.xrun.RestoreResponseB&Z$github.com/microvm/sandbox/api/protob\x06proto3"

var (
	file_api_proto_xrun_proto_rawDescOnce sync.Once
	file_api_proto_xrun_proto_rawDescData []byte
)

func file_api_proto_xrun_proto_rawDescGZIP() []byte {
	file_api_proto_xrun_proto_rawDescOnce.Do(func() {
		file_api_proto_xrun_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_xrun_proto_rawDesc), len(file_api_proto_xrun_proto_rawDesc)))
	})
	return file_api_proto_xrun_proto_rawDescData
}

var file_api_proto_xrun_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_proto_xrun_proto_goTypes = []any{
	(*RunRequest)(nil),       // 0: xrun.RunRequest
	(*RunResponse)(nil),      // 1: xrun.RunResponse
	(*StopRequest)(nil),      // 2: xrun.StopRequest
	(*StopResponse)(nil),     // 3: xrun.StopResponse
	(*DeleteRequest)(nil),    // 4: xrun.DeleteRequest
	(*DeleteResponse)(nil),   // 5: xrun.DeleteResponse
	(*GetRequest)(nil),       // 6: xrun.GetRequest
	(*GetResponse)(nil),      // 7: xrun.GetResponse
	(*ListRequest)(nil),      // 8: xrun.ListRequest
	(*ListResponse)(nil),     // 9: xrun.ListResponse
	(*Sandbox)(nil),          // 10: xrun.Sandbox
	(*SnapshotRequest)(nil),  // 11: xrun.SnapshotRequest
	(*SnapshotResponse)(nil), // 12: xrun.SnapshotResponse
	(*RestoreRequest)(nil),   // 13: xrun.RestoreRequest
	(*RestoreResponse)(nil),  // 14: xrun.RestoreResponse
	nil,                      // 15: xrun.RunRequest.LabelsEntry
	nil,                      // 16: xrun.ListRequest.FiltersEntry
	nil,                      // 17: xrun.Sandbox.LabelsEntry
	nil,                      // 18: xrun.SnapshotRequest.LabelsEntry
}
var file_api_proto_xrun_proto_depIdxs = []int32{
	15, // 0: xrun.RunRequest.labels:type_name -> xrun.RunRequest.LabelsEntry
	10, // 1: xrun.GetResponse.sandbox:type_name -> xrun.Sandbox
	16, // 2: xrun.ListRequest.filters:type_name -> xrun.ListRequest.FiltersEntry
	10, // 3: xrun.ListResponse.sandboxes:type_name -> xrun.Sandbox
	17, // 4: xrun.Sandbox.labels:type_name -> xrun.Sandbox.LabelsEntry
	18, // 5: xrun.SnapshotRequest.labels:type_name -> xrun.SnapshotRequest.LabelsEntry
	0,  // 6: xrun.SandboxService.Run:input_type -> xrun.RunRequest
	2,  // 7: xrun.SandboxService.Stop:input_type -> xrun.StopRequest
	4,  // 8: xrun.SandboxService.Delete:input_type -> xrun.DeleteRequest
	6,  // 9: xrun.SandboxService.Get:input_type -> xrun.GetRequest
	8,  // 10: xrun.SandboxService.List:input_type -> xrun.ListRequest
	11, // 11: xrun.SandboxService.Snapshot:input_type -> xrun.SnapshotRequest
	13, // 12: xrun.SandboxService.Restore:input_type -> xrun.RestoreRequest
	1,  // 13: xrun.SandboxService.Run:output_type -> xrun.RunResponse
	3,  // 14: xrun.SandboxService.Stop:output_type -> xrun.StopResponse
	5,  // 15: xrun.SandboxService.Delete:output_type -> xrun.DeleteResponse
	7,  // 16: xrun.SandboxService.Get:output_type -> xrun.GetResponse
	9,  // 17: xrun.SandboxService.List:output_type -> xrun.ListResponse
	12, // 18: xrun.SandboxService.Snapshot:output_type -> xrun.SnapshotResponse
	14, // 19: xrun.SandboxService.Restore:output_type -> xrun.RestoreResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_xrun_proto_init() }
func file_api_proto_xrun_proto_init() {
	if File_api_proto_xrun_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_xrun_proto_rawDesc), len(file_api_proto_xrun_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_xrun_proto_goTypes,
		DependencyIndexes: file_api_proto_xrun_proto_depIdxs,
		MessageInfos:      file_api_proto_xrun_proto_msgTypes,
	}.Build()
	File_api_proto_xrun_proto = out.File
	file_api_proto_xrun_proto_goTypes = nil
	file_api_proto_xrun_proto_depIdxs = nil
}
